### PR TITLE
10 run algorithm view

### PR DESCRIPTION
**Pull request by andrew-wagner89**
npm install
npm start
check that /Landing takes you to /runplacements, not /placements

check that view and run take you to /placements/:grade, where grade is the grade chosen
as of now run and view will not display placement results since placements is not complete

### CODE REVIEW

**Comment by andrew-wagner89** [comment]
@Jacquelinereverand @acmccuaig @jamesvclements

**Comment by andrew-wagner89** [comment]
Your .env file should have the following line appended to it:
REACT_APP_SERVER_ADDRESS=http://localhost:8080

**Comment by jamesvclements** [comment]
I'm going to switch these in to their own components using the bootstrap `<Panel>`

**Comment by jamesvclements** [comment]
:shipit:

**Pull request merged**
